### PR TITLE
use constructor injection instead of @Inject for v4 compatibility

### PR DESCRIPTION
**Pull request by ruddell**
This updates the module to work with v4 (at least the Java resource and service)

For Angular 2 apps, the frontend files are skipped as they are Angular 1

### CODE REVIEW

**Comment by geraldhumphries** [comment]
Are you planning on adding new frontend files for A2 apps in this PR? That will need to be done eventually. If not, I can merge right away and the A2 work can be done separately.

**Comment by ruddell** [comment]
Maybe sometime down the road but not in this PR, I don't have any Angular 2 projects.

**Comment by geraldhumphries** [comment]
I think we should also continue to use field injection for <v4 apps. Even if field injection has a lot of disadvantages, I would prefer consistency in my apps. Two files using constructor injection while everything else uses field injection would be an annoyance that can easily be avoided.

I would refactor the `versionTwo` boolean into a version integer. The initial JH module support didn't have the version number so the version two test should remain as it is, but version three and four can simply read the version provided by JH. Use field injection if `version < 4`, otherwise use constructor injection.

**Comment by ruddell** [comment]
Updated to handle all versions

**Pull request merged**
